config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("ecommerce.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("shop/", include("ecommerce.shop.urls", namespace="shop")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]
urlpatterns += [
    path('api/token/',
         jwt_views.TokenObtainPairView.as_view(),
         name ='token_obtain_pair'),
    path('api/token/refresh/',
         jwt_views.TokenRefreshView.as_view(),
         name ='token_refresh'),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ecommerce/shop/urls.py
from django.urls import path
from ecommerce.shop.views import *
from ecommerce.shop.api.views import *
app_name = "shop"
urlpatterns = [
    path("", ShopView.as_view(), name="index"),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('invoice/', ListInvoice.as_view(), name='list-invoice'),
    path('check-out/', check_out_order, name='check-out'),
    path('add-to-cart/<slug:slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug:slug>/', remove_from_cart, name='remove-from-cart'),
    path('check-address/', check_address, name='address'),
    path('<slug:slug>/', ItemDetailView.as_view(), name='product'),

]

ecommerce/users/urls.py
from django.urls import path

from ecommerce.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

ecommerce/shop/models.py
from django.db import models
from django.shortcuts import reverse
from django.conf import settings
from django_countries.fields import CountryField
from django.template.defaultfilters import slugify
# Create your models here.


class Category(models.Model):


    name = models.CharField(blank=False, null=False,max_length=20)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Product(models.Model):

    title = models.CharField(max_length=50)
    price = models.FloatField()
    category = models.ForeignKey(Category, null = False, on_delete=models.CASCADE)
    describe = models.TextField(default = 'New Product')
    picture = models.ImageField()
    slug = models.SlugField(null=False, unique=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs): # new
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def get_product_url(self):

        return reverse("shop:product",kwargs={
            'slug': self.slug,
        })

    def get_add_to_cart_url(self):
        return reverse("shop:add-to-cart", kwargs={
        'slug': self.slug
    })

    def get_remove_from_cart_url(self):
        return reverse("shop:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):


    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

class Order(models.Model):


    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_item_price()
        return total

class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    zip = models.CharField(max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

ecommerce/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):

    error_message = admin_forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

ecommerce/shop/api/views.py
from rest_framework import viewsets,permissions
from rest_framework import status
from rest_framework.response import Response
from rest_framework.generics import get_object_or_404
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.decorators import action
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from .serializers import OrderSerializers, ProductSerializers, OrderItemSerializers
from ecommerce.shop.models import Product, Order, OrderItem

User = get_user_model()
class ProductViewSet(viewsets.ModelViewSet):

    queryset = Product.objects.all()
    serializer_class = ProductSerializers
    permission_classes = (IsAuthenticated,)

class OrderViewSet(viewsets.ViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializers

    def list(self, request):
        serializer = self.serializer_class(self.queryset, many=True)
        return Response(serializer.data)

    def retrieve(self, request, pk=id):
        order = get_object_or_404(self.queryset, pk=pk)
        serializer = self.serializer_class(order)
        return Response(serializer.data)

    def create(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data, status=status.HTTP_201_CREATED)

class OrderItemViewSet(viewsets.ViewSet):

    queryset = OrderItem.objects.all()
    serializer_class = OrderItemSerializers

    def list(self, request):
        serializer = self.serializer_class(self.queryset, many=True)
        return Response(
            serializer.data
            )

    def retrieve(self, request, pk=id):
        order = get_object_or_404(self.queryset, pk=pk)
        serializer = self.serializer_class(order)
        return Response(serializer.data)

    def create(self, request, *args, **kwargs):
        # item = get_object_or_404(Product, id=request.data.get("product_id"))
        # order_item, created = OrderItem.objects.get_or_create(
        #     item =item,
        #     user = request.user,
        #     ordered = False,
        # )
        product_id = int(request.data.get("item_id"))
        item = Product.objects.get(id = product_id)
        if item.id == product_id:
            order_qs = OrderItem.objects.get(user = request.user,item = item)
            quantity = int(request.data["quantity"]) + order_qs.quantity
            order_qs.quantity = quantity
            order_qs.save()
            serializer = self.serializer_class(order_qs)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            serializer = self.serializer_class(data=request.data)
            if serializer.is_valid(raise_exception=True):
                serializer.save(user=request.user)
            return Response(serializer.data, status=status.HTTP_201_CREATED)

    def partial_update(self, request, *args, **kwargs):
        instance = self.queryset.get(pk=kwargs.get('pk'))
        serializer = self.serializer_class(instance, data=request.data, partial=True)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)

ecommerce/shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.generic import ListView, DetailView, View
from ecommerce.shop.models import Product, Order, OrderItem, Address, Category
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.


class ShopView(ListView):
    model = Product
    paginate_by = 12
    ordering = ['id']
    template_name = "shop/product.html"

class ItemDetailView(DetailView):

    model = Product
    template_name = "shop/product-detail.html"


class OrderSummaryView(LoginRequiredMixin,View):

    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, being_delivered=False)
            context = {
                'object': order
            }
            return render(self.request, 'shop/cart.html', context)
        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order")
            return redirect("/")


@login_required
def add_to_cart(request,slug):

    item = get_object_or_404(Product, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item =item,
        user = request.user,
        ordered = False
    )
    order_history = Order.objects.filter(user=request.user, being_delivered=False)
    if order_history.exists():
        order = order_history[0]
        if order.items.filter(item__slug = item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "This item quantity was updated.")
            return redirect("shop:order-summary")
        else:
            order.items.add(order_item)
            messages.info(request, "This item was added to your cart.")
            return redirect("shop:order-summary")
    else:
        order = Order.objects.create(user=request.user)
        order.items.add(order_item)
        messages.info(request, "This item was added to your cart.")
        return redirect("shop:order-summary")

@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Product, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        being_delivered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            order.items.remove(order_item)
            order_item.delete()
            messages.info(request, "This item was removed from your cart.")
            return redirect("shop:order-summary")
        else:
            messages.info(request, "This item was not in your cart")
            return redirect("shop:product", slug=slug)
    else:
        messages.info(request, "You do not have an active order")
        return redirect("shop:product", slug=slug)



class ListInvoice(ListView):
    model = Order
    template_name = 'shop/invoice.html'

@login_required
def check_address(request):
    return render(request, 'shop/form-address.html')

def check_out_order(request):
    if request.method == 'POST':
        city = request.POST.get("City")
        province = request.POST.get("Province")
        street = request.POST.get("Street")
        zip_code = request.POST.get("Zip")

        address = Address(
            user= request.user,
            country=city,
            street_address=street,
            apartment_address=province,
            zip=zip_code,
        )
        address.save()
        # order_bill.shipping_address.add(address)
        # order_bill.being_delivered = True
        # order_bill.save()
        order_bill = Order.objects.get(user= request.user, being_delivered=False)
        order_bill.shipping_address = address
        order_bill.save()
        context = {
            'object' : order_bill,
            'order_item'  : order_bill.items.all()
        }
        return render(request, 'shop/checkout.html', context = context)
    else:
         return redirect("/")

ecommerce/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet
from .serializers import UserSerializer


User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

ecommerce/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

ecommerce/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}ECommerce{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{% static 'css/font.css' %}" rel="stylesheet"> {% block css %}
    <!-- Your stuff: Third-party CSS libraries go here -->
    <link href="{% static 'css/_grid.css' %}" rel="stylesheet">
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/project.css' %}" rel="stylesheet"> {% endblock %}

</head>

<body>

    {% if messages %} {% for message in messages %}
    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
    {% endfor %} {% endif %}
    <!--Start Header-->
    <div class="header">
        <div class="container">
            <div class="navbar">
                <div class="logo">
                    <a href="{% url 'home' %}"><img src="{% static 'images/logo.png' %}" alt="Logo"></a>
                </div>
                <nav>
                    <ul id="MenuItems">
                        <li><a href="{% url 'home' %}">Home</a></li>
                        <li><a href="{% url 'shop:index' %}">Product</a></li>
                        <li><a href="{% url 'about' %}">About</a></li>
                        {% if request.user.is_authenticated %}
                        <li>
                            {# URL provided by django-allauth/account/urls.py #}
                            <a href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
                        </li>
                        <li>
                          {# URL provided by django-allauth/account/urls.py #}
                          <a href="{% url 'shop:list-invoice'%}">{% trans "My Invoice" %}</a>
                      </li>
                        <li>
                            {# URL provided by django-allauth/account/urls.py #}
                            <a href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
                        </li>
                        {% else %}
                        <li>
                            {# URL provided by django-allauth/account/urls.py #}
                            <a id="sign-up-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                        </li>
                        <li>
                            {# URL provided by django-allauth/account/urls.py #}
                            <a id="log-in-link" href="{% url 'account_login' %} ">{% trans "Sign In " %}</a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
                <img src="{% static 'images/cart.png' %} " alt=" ">
                <img src="{% static 'images/menu.png' %}" class="menu-icon " onclick="menutoggle() ">
            </div>
            {% block home %} {% endblock home %}

        </div>
    </div>
    <!--End Header-->
    {% block account %} {% endblock account %}

    <!-- /container -->
    {% block modal %}{% endblock modal %}
    <!--Start Footer-->
    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="footer-col-1">
                    <h3>Download Our App</h3>
                    <p>Download App for Android and ios mobile phone.</p>
                    <div class="app-logo">
                        <img src="{% static 'images/play-store.png' %}">
                        <img src="{% static 'images/app-store.png' %}">
                    </div>
                </div>
                <div class="footer-col-2">
                    <img src="{% static 'images/logo-white.png' %}" alt="">
                    <p>Our Purpose Is To Sustainably Make the Pleasure and Benefits of Sports Accesible to the Many.
                    </p>
                </div>
                <div class="footer-col-3">
                    <h3>Useful Links</h3>
                    <ul>
                        <li>Coupons</li>
                        <li>Blog Post</li>
                        <li>Return Policy</li>
                        <li>Join Affiliate</li>
                    </ul>
                </div>
                <div class="footer-col-4">
                    <h3>Follow Us</h3>
                    <ul>
                        <li>Facebook</li>
                        <li>Twitter</li>
                        <li>Instagram</li>
                        <li>Youtube</li>
                    </ul>
                </div>
            </div>
            <hr>
            <p class="copyright">Copyright 2020 - Easy Tutoriasl</p>
        </div>
    </div>
    <!--End Footer-->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}

    <!-- Bootstrap JS and its dependencies-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- Your stuff: Third-party javascript libraries go here -->


    <!-- place project specific Javascript in this file -->

    <script src="{% static 'js/project.js' %}"></script>


    {% endblock javascript %}

</body>

</html>